import { Cell, CellType } from "./stage.ts";

export const stages = [
  [ // 1
    [
      [CellType.Start, 0, 0],
      [CellType.Plane],
      [CellType.Plane],
      [CellType.Mirror, 0, 2],
    ],
    [
      [CellType.None],
      [CellType.None],
      [CellType.Plane],
    ],
    [
      [CellType.None],
      [CellType.Mirror, 1, 5],
      [CellType.Plane],
      [CellType.Plane],
      [CellType.Goal, 0, 0],
    ],
  ],
  [ // 2
    [
      [CellType.None],
      [CellType.None],
      [CellType.Mirror, 1, 1],
      [CellType.Plane],
      [CellType.Mirror, 1, 3],
    ],
    [
      [CellType.None],
      [CellType.None],
      [CellType.Plane],
      [CellType.Plane],
    ],
    [
      [CellType.None],
      [CellType.None],
      [CellType.Goal, 0, 3],
      [CellType.Plane],
      [CellType.Mirror, 1, 5],
    ],
    [
      [CellType.None],
      [CellType.Plane],
      [CellType.Plane],
      [CellType.Plane],
    ],
    [
      [CellType.Start, 0, 5],
      [CellType.None],
      [CellType.Mirror, 1, 4],
    ],
  ],
  [ // 3
    [
      [CellType.None],
      [CellType.None],
      [CellType.None],
      [CellType.Mirror, 0, 0],
    ],
    [
      [CellType.None],
      [CellType.Mirror, 0, 4],
      [CellType.Mirror, 1, 5],
      [CellType.Mirror, 0, 1],
      [CellType.Mirror, 0, 2],
    ],
    [
      [CellType.None],
      [CellType.Start, 0, 4],
      [CellType.Mirror, 0, 0],
      [CellType.Goal, 0, 4],
    ],
    [
      [CellType.Mirror, 0, 2],
      [CellType.Mirror, 0, 1],
      [CellType.Mirror, 0, 5],
      [CellType.Mirror, 0, 4],
    ],
    [
      [CellType.None],
      [CellType.Mirror, 0, 0],
    ],
  ],
  [ // 4
    [
      [CellType.Start, 0, 1],
      [CellType.None],
      [CellType.Goal, 0, 5],
    ],
    [
      [CellType.Plane],
      [CellType.Plane],
    ],
    [
      [CellType.HalfMirror, 1, 3],
    ],
    [
      [CellType.Plane],
    ],
    [
      [CellType.Goal, 0, 1],
    ],
  ],
  [ // 5
    [
      [CellType.None],
      [CellType.None],
      [CellType.Start, 0, 1],
    ],
    [
      [CellType.None],
      [CellType.None],
      [CellType.Plane],
    ],
    [
      [CellType.Goal, 0, 3],
      [CellType.Plane],
      [CellType.HalfMirror, 1, 3],
      [CellType.Plane],
      [CellType.Mirror, 0, 3],
    ],
    [
      [CellType.None],
      [CellType.None],
      [CellType.Plane],
    ],
    [
      [CellType.None],
      [CellType.None],
      [CellType.Mirror, 0, 5],
    ],
  ],
  [ // 6
    [
      [CellType.Start, 0, 0],
      [CellType.Plane],
      [CellType.HalfMirror, 0, 2],
      [CellType.Plane],
      [CellType.Mirror, 0, 2],
    ],
    [
      [CellType.None],
      [CellType.Plane],
      [CellType.None],
      [CellType.Plane],
    ],
    [
      [CellType.Mirror, 1, 0],
      [CellType.Plane],
      [CellType.HalfMirror, 1, 3],
      [CellType.Plane],
      [CellType.Goal, 0, 0],
    ],
  ],
  [ // 7
    [
      [CellType.Start, 0, 0],
      [CellType.Plane],
      [CellType.HalfMirror, 0, 2],
      [CellType.Z, 1, 0],
      [CellType.Mirror, 0, 2],
    ],
    [
      [CellType.None],
      [CellType.Plane],
      [CellType.None],
      [CellType.Plane],
    ],
    [
      [CellType.Mirror, 0, 2],
      [CellType.Z, 0, 1],
      [CellType.HalfMirror, 0, 2],
      [CellType.Plane],
      [CellType.Goal, 0, 0],
    ],
  ],
  [ // 8
    [
      [CellType.None],
      [CellType.None],
      [CellType.Start, 0, 0],
      [CellType.Plane],
      [CellType.HalfMirror, 0, 2],
      [CellType.Plane],
      [CellType.HalfMirror, 0, 2],
      [CellType.S, 0, 1],
      [CellType.Mirror, 0, 2],
    ],
    [
      [CellType.None],
      [CellType.None],
      [CellType.None],
      [CellType.Plane],
      [CellType.None],
      [CellType.S, 1, 1],
      [CellType.None],
      [CellType.Z, 0, 1],
    ],
    [
      [CellType.None],
      [CellType.None],
      [CellType.HalfMirror, 0, 2],
      [CellType.S, 1, 1],
      [CellType.Plane],
      [CellType.Z, 1, 1],
      [CellType.HalfMirror, 0, 2],
    ],
    [
      [CellType.None],
      [CellType.S, 1, 1],
      [CellType.None],
      [CellType.Z, 1, 1],
      [CellType.None],
      [CellType.Plane],
    ],
    [
      [CellType.Mirror, 0, 2],
      [CellType.Z, 1, 1],
      [CellType.HalfMirror, 0, 2],
      [CellType.Plane],
      [CellType.HalfMirror, 0, 2],
      [CellType.Plane],
      [CellType.Goal, 0, 0],
    ],
  ],
  [ // 9
    [
      [CellType.None],
      [CellType.None],
      [CellType.Start, 0, 1],
      [CellType.None],
      [CellType.Mirror, 0, 0],
      [CellType.None],
      [CellType.Mirror, 0, 1],
    ],
    [
      [CellType.None],
      [CellType.None],
      [CellType.Plane],
      [CellType.T, 1, 1],
      [CellType.Plane],
      [CellType.T, 1, 1],
    ],
    [
      [CellType.None],
      [CellType.None],
      [CellType.HalfMirror, 0, 0],
      [CellType.None],
      [CellType.HalfMirror, 0, 0],
    ],
    [
      [CellType.None],
      [CellType.Plane],
      [CellType.S, 1, 1],
      [CellType.Plane],
      [CellType.S, 1, 1],
    ],
    [
      [CellType.Goal, 0, 2],
      [CellType.None],
      [CellType.Mirror, 0, 0],
      [CellType.None],
      [CellType.Mirror, 0, 5],
    ],
  ],
  [ // 10
    [
      [CellType.None],
      [CellType.None],
      [CellType.Mirror, 0, 5],
      [CellType.Start, 0, 0],
      [CellType.Mirror, 0, 1],
      [CellType.None],
      [CellType.Mirror, 0, 5],
      [CellType.S, 1, 0],
      [CellType.Mirror, 0, 1],
    ],
    [
      [CellType.None],
      [CellType.T, 1, 1],
      [CellType.None],
      [CellType.None],
      [CellType.HalfMirror, 0, 5],
      [CellType.HalfMirror, 0, 1],
      [CellType.None],
      [CellType.None],
      [CellType.Plane],
    ],
    [
      [CellType.Mirror, 0, 3],
      [CellType.None],
      [CellType.None],
      [CellType.None],
      [CellType.Plane],
      [CellType.None],
      [CellType.None],
      [CellType.None],
      [CellType.Mirror, 0, 3],
    ],
    [
      [CellType.Z, 1, 1],
      [CellType.None],
      [CellType.None],
      [CellType.Plane],
      [CellType.Plane],
      [CellType.None],
      [CellType.None],
      [CellType.T, 0, 1],
    ],
    [
      [CellType.Mirror, 0, 1],
      [CellType.S, 0, 1],
      [CellType.Mirror, 0, 5],
      [CellType.None],
      [CellType.Mirror, 0, 1],
      [CellType.Goal, 0, 3],
      [CellType.Mirror, 0, 5],
    ],
  ],
  [ // 11
    [
      [CellType.Mirror, 0, 4],
      [CellType.Start, 0, 0],
      [CellType.HalfMirror, 1, 5],
      [CellType.Mirror, 0, 1],
    ],
    [
      [CellType.Plane],
      [CellType.None],
      [CellType.Mirror, 0, 1],
      [CellType.HalfMirror, 1, 3],
      [CellType.Mirror, 0, 1],
    ],
    [
      [CellType.Plane],
      [CellType.None],
      [CellType.None],
      [CellType.Mirror, 0, 1],
      [CellType.HalfMirror, 1, 3],
    ],
    [
      [CellType.HalfMirror, 0, 4],
      [CellType.Plane],
      [CellType.Plane],
      [CellType.Plane],
      [CellType.Mirror, 0, 4],
    ],
    [
      [CellType.Goal, 0, 1],
    ],
  ],
  [ // 12
    [
      [CellType.None],
      [CellType.None],
      [CellType.None],
      [CellType.None],
      [CellType.None],
      [CellType.None],
      [CellType.None],
      [CellType.None],
      [CellType.Mirror, 0, 5],
    ],
    [
      [CellType.None],
      [CellType.None],
      [CellType.None],
      [CellType.None],
      [CellType.None],
      [CellType.None],
      [CellType.None],
      [CellType.None],
      [CellType.Plane],
      [CellType.None],
      [CellType.None],
      [CellType.Mirror, 0, 1],
    ],
    [
      [CellType.None],
      [CellType.None],
      [CellType.None],
      [CellType.None],
      [CellType.None],
      [CellType.None],
      [CellType.None],
      [CellType.None],
      [CellType.Plane],
      [CellType.None],
      [CellType.Plane],
    ],
    [
      [CellType.None],
      [CellType.None],
      [CellType.None],
      [CellType.None],
      [CellType.None],
      [CellType.None],
      [CellType.None],
      [CellType.None],
      [CellType.HalfMirror, 0, 5],
      [CellType.Plane],
    ],
    [
      [CellType.Mirror, 0, 3],
      [CellType.Goal, 0, 0],
      [CellType.Start, 0, 0],
      [CellType.HalfMirror, 0, 3],
      [CellType.Plane],
      [CellType.Plane],
      [CellType.HalfMirror, 0, 3],
      [CellType.Plane],
      [CellType.Mirror, 1, 1],
    ],
    [
      [CellType.None],
      [CellType.None],
      [CellType.None],
      [CellType.None],
      [CellType.None],
      [CellType.None],
      [CellType.None],
      [CellType.Plane],
      [CellType.S, 0, 1],
    ],
    [
      [CellType.None],
      [CellType.None],
      [CellType.None],
      [CellType.None],
      [CellType.None],
      [CellType.None],
      [CellType.HalfMirror, 0, 1],
      [CellType.None],
      [CellType.Mirror, 0, 5],
    ],
    [
      [CellType.None],
      [CellType.None],
      [CellType.None],
      [CellType.None],
      [CellType.None],
      [CellType.Plane],
    ],
    [
      [CellType.None],
      [CellType.None],
      [CellType.None],
      [CellType.None],
      [CellType.Mirror, 0, 1],
    ],
  ],
] as const satisfies Cell[][][];
